---
# tasks file for common
- include_tasks: setproxy.yml
  when: location== "28lab"

- name: Install epel
  yum:
    name: epel-release
    state: latest

- name: Install all core packages
  yum:
    name: [httpd, net-tools, bind-utils, telnet, python, dnsmasq, autossh, ntp, python-setuptools, python2-pip, python-devel]
    state: present

- name: upgrade pip (command line)
  shell: pip install --upgrade pip
  tags: easy_install

- name: upgrade setuptools (command line)
  shell: pip install --upgrade setuptools
  tags: easy_install

- name: Install Virtualenv (pip)
  pip:
    name: virtualenv
  tags: pip

- name: Install Ansible
  pip:
    name: ansible
  tags: pip
    
- name: yum update all packages
  yum:
    name: '*'
    state: latest
    
- name: modify hostname
  include_tasks: hostname.yml

  #- name: modify dnsmasq conf (dns, email server, tftp server)

